### ISSUE TITLE
Bump to kernel 4.14

### ISSUE THREAD

**Issue by avafinger** [rafaello7/linux-nanopi-m3#4]
@rafaello7 
Do you plan to move your work to 4.14? Just asking.

**Comment by rafaello7** [comment]
I do not have precise plans related to kernel update. Although it is possible, when I will have a strong motivation. Currently I haven't. I think it would be simpler than porting 4.4 kernel to 4.11, so maybe... A lot here depends on my mood ;)

**Comment by avafinger** [comment]
Ok, Got that. You can close this or leave it open until you decide. Thanks.

**Comment by rafaello7** [comment]
You may test [the 4.14.3 kernel](https://github.com/rafaello7/linux-nanopi-m3-v4.14/releases)

**Comment by avafinger** [comment]
@rafaello7 , you are fast! Will try to test this and give you some feedback. Thank you.

**Comment by rafaello7** [comment]
It is not my first try of 4.14 line, I made some preliminary tests a few weeks ago using version 4.14-rc3. Hence it was little easier now for me ;)

I thought about kernel upgrade much earlier, when I have noticed that 4.11 line disappeared. I waited for kernel with long-term support. It looks this line will not disappear till Jan 2020. But I also hesitated, since 4.11 kernel works pretty.
